apiVersion: v1
kind: Service
metadata:
  labels:
    app: marabet-ai
    environment: staging
  name: marabet-ai-staging-service
  namespace: marabet-staging
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: marabet-ai
    environment: staging
  type: ClusterIP
