apiVersion: v1
data:
  app.conf: '

    [app]

    debug = false

    host = 0.0.0.0

    port = 5000


    [database]

    pool_size = 20

    max_overflow = 30

    pool_timeout = 30

    pool_recycle = 3600


    [redis]

    max_connections = 20

    socket_timeout = 5

    socket_connect_timeout = 5


    [logging]

    level = INFO

    format = %(asctime)s - %(name)s - %(levelname)s - %(message)s

    '
kind: ConfigMap
metadata:
  name: marabet-config
  namespace: marabet
