apiVersion: v1
kind: Service
metadata:
  name: marabet-ai-service
  namespace: marabet
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: marabet-ai
  type: ClusterIP
