global:
  evaluation_interval: 15s
  scrape_interval: 15s
rule_files:
- rules/*.yml
scrape_configs:
- job_name: marabet-app
  metrics_path: /api/metrics
  scrape_interval: 5s
  static_configs:
  - targets:
    - app:5000
- job_name: redis
  scrape_interval: 15s
  static_configs:
  - targets:
    - redis:6379
- job_name: postgres
  scrape_interval: 15s
  static_configs:
  - targets:
    - postgres:5432
